// Inline mock data so the frontend renders without backend or env config.
// Mirrors the RawEvent → Event normalization for UI purposes.

import type { Event, SourceRunLog, Subscription, Bookmark } from './types';

const now = new Date();
const day = 24 * 60 * 60 * 1000;

function iso(offsetDays: number, hour = 19, minute = 0): string {
  const d = new Date(now.getTime() + offsetDays * day);
  d.setUTCHours(hour - 9, minute, 0, 0); // KST = UTC+9
  return d.toISOString();
}

export const MOCK_EVENTS: Event[] = [
  {
    id: 'mock-luma-1',
    source: 'luma',
    source_event_id: 'lc-kr-meetup-5',
    source_url: 'https://lu.ma/langchain-korea-5',
    title: 'LangChain Korea Meetup #5 — RAG in Production',
    description: '실서비스 RAG 운영 경험을 공유하는 밋업. 검색 품질, 비용 최적화, 평가 자동화까지 다룹니다.',
    start_at: iso(2, 19, 0),
    end_at: iso(2, 22, 0),
    timezone: 'Asia/Seoul',
    location_type: 'offline',
    location_name: '강남구 역삼동 메리츠타워 5F',
    city: '서울',
    country: 'KR',
    host_name: 'LangChain Korea',
    price: '무료',
    categories: ['LLM', 'RAG', 'Meetup'],
    keywords_matched: ['LangChain', 'RAG', 'LLM'],
    thumbnail_url: null,
    is_ai_related: true,
    collected_at: iso(-1, 3, 0),
  },
  {
    id: 'mock-festa-1',
    source: 'festa',
    source_event_id: 'pytorch-kr-conf',
    source_url: 'https://festa.io/events/pytorch-kr-2026',
    title: 'PyTorch Korea Conference 2026',
    description: '국내 최대 규모의 PyTorch 사용자 컨퍼런스. 멀티모달, 디퓨전, 효율화 세션 다수.',
    start_at: iso(14, 10, 0),
    end_at: iso(14, 18, 0),
    timezone: 'Asia/Seoul',
    location_type: 'offline',
    location_name: 'COEX 그랜드볼룸',
    city: '서울',
    country: 'KR',
    host_name: 'PyTorch Korea',
    price: '50,000원',
    categories: ['AI', 'ML', 'Conference'],
    keywords_matched: ['PyTorch', 'Diffusion'],
    thumbnail_url: null,
    is_ai_related: true,
    collected_at: iso(-1, 3, 0),
  },
  {
    id: 'mock-devpost-1',
    source: 'devpost',
    source_event_id: 'global-agent-hack',
    source_url: 'https://devpost.com/hackathons/global-agent-hack-2026',
    title: 'Global Agent Hackathon 2026',
    description: 'Build autonomous AI agents. $50,000 prize pool. Sponsored by major AI labs.',
    start_at: iso(5, 9, 0),
    end_at: iso(7, 21, 0),
    timezone: 'America/Los_Angeles',
    location_type: 'online',
    location_name: 'Online',
    city: 'Online',
    country: 'GLOBAL',
    host_name: 'Devpost',
    price: 'Free',
    categories: ['Agent', 'Hackathon', 'LLM'],
    keywords_matched: ['Agent', 'Autonomous', 'LLM'],
    thumbnail_url: null,
    is_ai_related: true,
    collected_at: iso(-1, 3, 0),
  },
  {
    id: 'mock-eventus-1',
    source: 'eventus',
    source_event_id: 'enterprise-ai-summit',
    source_url: 'https://event-us.kr/eai/event/89321',
    title: '엔터프라이즈 AI 서밋 2026 — LLMOps & On-prem',
    description: '기업 AI 도입 사례, LLMOps 파이프라인, 보안 거버넌스 트랙으로 구성된 1일 컨퍼런스.',
    start_at: iso(21, 9, 30),
    end_at: iso(21, 17, 30),
    timezone: 'Asia/Seoul',
    location_type: 'hybrid',
    location_name: '판교 H스퀘어 N동 대강당',
    city: '판교',
    country: 'KR',
    host_name: 'AI Korea Forum',
    price: '120,000원',
    categories: ['MLOps', 'LLM', 'Conference'],
    keywords_matched: ['LLMOps', 'Enterprise'],
    thumbnail_url: null,
    is_ai_related: true,
    collected_at: iso(-1, 3, 0),
  },
  {
    id: 'mock-dev-event-1',
    source: 'dev_event',
    source_event_id: 'mlops-community-1',
    source_url: 'https://github.com/brave-people/Dev-Event',
    title: 'MLOps Community Korea 정기 모임 #12',
    description: 'Vector DB 운영 사례, Feature Store 도입기, MLflow 활용 트랙.',
    start_at: iso(9, 19, 30),
    end_at: iso(9, 22, 0),
    timezone: 'Asia/Seoul',
    location_type: 'offline',
    location_name: '서울 성수동 패스트파이브 성수점',
    city: '서울',
    country: 'KR',
    host_name: 'MLOps Korea',
    price: '무료',
    categories: ['MLOps', 'Meetup'],
    keywords_matched: ['MLOps', 'Vector DB', 'MLflow'],
    thumbnail_url: null,
    is_ai_related: true,
    collected_at: iso(-1, 3, 0),
  },
  {
    id: 'mock-luma-2',
    source: 'luma',
    source_event_id: 'multimodal-online',
    source_url: 'https://lu.ma/multimodal-2026',
    title: 'Multimodal AI Workshop — Vision × Language',
    description: 'CLIP, Florence, Gemini Vision API 실습. Colab 사전 환경 제공.',
    start_at: iso(0, 21, 0), // 오늘
    end_at: iso(0, 23, 0),
    timezone: 'UTC',
    location_type: 'online',
    location_name: 'Online (Zoom)',
    city: 'Online',
    country: 'GLOBAL',
    host_name: 'Multimodal AI',
    price: '$20',
    categories: ['Vision', 'LLM', 'Workshop'],
    keywords_matched: ['Multimodal', 'Vision'],
    thumbnail_url: null,
    is_ai_related: true,
    collected_at: iso(-1, 3, 0),
  },
  {
    id: 'mock-festa-2',
    source: 'festa',
    source_event_id: 'ai-product-design',
    source_url: 'https://festa.io/events/ai-pd-2026',
    title: 'AI 프로덕트 디자인 세미나 — Copilot 패턴',
    description: 'AI 기능을 제품에 자연스럽게 녹이는 UX 패턴. PM/디자이너 대상.',
    start_at: iso(3, 14, 0),
    end_at: iso(3, 18, 0),
    timezone: 'Asia/Seoul',
    location_type: 'offline',
    location_name: '성수동 디자인뮤지엄',
    city: '서울',
    country: 'KR',
    host_name: 'AI PD Society',
    price: '30,000원',
    categories: ['AI', 'Design', 'Seminar'],
    keywords_matched: ['Copilot', 'AI UX'],
    thumbnail_url: null,
    is_ai_related: true,
    collected_at: iso(-1, 3, 0),
  },
  {
    id: 'mock-devpost-2',
    source: 'devpost',
    source_event_id: 'rag-bench',
    source_url: 'https://devpost.com/hackathons/rag-bench-2026',
    title: 'RAG Benchmark Challenge — Build the Best Retriever',
    description: 'Push the boundaries of retrieval. $25k prize. Eval harness provided.',
    start_at: iso(35, 9, 0),
    end_at: iso(45, 23, 0),
    timezone: 'UTC',
    location_type: 'online',
    location_name: 'Online',
    city: 'Online',
    country: 'GLOBAL',
    host_name: 'RAG Bench Org',
    price: 'Free',
    categories: ['RAG', 'Hackathon', 'LLM'],
    keywords_matched: ['RAG', 'Retrieval'],
    thumbnail_url: null,
    is_ai_related: true,
    collected_at: iso(-1, 3, 0),
  },
  {
    id: 'mock-eventus-2',
    source: 'eventus',
    source_event_id: 'gen-ai-week',
    source_url: 'https://event-us.kr/eai/event/91002',
    title: 'Generative AI Week — 4일 컨퍼런스',
    description: '생성형 AI 전반 트렌드, 케이스 스터디, 데모데이를 아우르는 1주짜리 페스티벌.',
    start_at: iso(28, 10, 0),
    end_at: iso(31, 18, 0),
    timezone: 'Asia/Seoul',
    location_type: 'offline',
    location_name: 'COEX 컨퍼런스룸',
    city: '서울',
    country: 'KR',
    host_name: 'Gen AI Week',
    price: '180,000원',
    categories: ['LLM', 'Conference', 'AI'],
    keywords_matched: ['Generative AI', 'Diffusion'],
    thumbnail_url: null,
    is_ai_related: true,
    collected_at: iso(-1, 3, 0),
  },
  {
    id: 'mock-dev-event-2',
    source: 'dev_event',
    source_event_id: 'pseudo-lab-onboard',
    source_url: 'https://github.com/brave-people/Dev-Event',
    title: '가짜연구소 (Pseudo Lab) 8기 모집 안내',
    description: 'AI 논문 스터디 및 오픈소스 프로젝트. 16주 운영, 마감 D-3.',
    start_at: iso(3, 0, 0),
    end_at: iso(3, 23, 59),
    timezone: 'Asia/Seoul',
    location_type: 'online',
    location_name: 'Online',
    city: 'Online',
    country: 'KR',
    host_name: 'Pseudo Lab',
    price: '무료',
    categories: ['AI', 'ML', 'Community'],
    keywords_matched: ['AI', 'Open Source'],
    thumbnail_url: null,
    is_ai_related: true,
    collected_at: iso(-1, 3, 0),
  },
  {
    id: 'mock-luma-3',
    source: 'luma',
    source_event_id: 'sf-agent-night',
    source_url: 'https://lu.ma/sf-agent-night',
    title: 'SF Agent Night — Demo & Drinks',
    description: 'Live demos of autonomous agents. Networking with founders.',
    start_at: iso(7, 19, 0),
    end_at: iso(7, 23, 0),
    timezone: 'America/Los_Angeles',
    location_type: 'offline',
    location_name: 'Shack15, Ferry Building',
    city: 'San Francisco',
    country: 'US',
    host_name: 'Agent SF',
    price: 'Free',
    categories: ['Agent', 'Meetup'],
    keywords_matched: ['Agent', 'Autonomous'],
    thumbnail_url: null,
    is_ai_related: true,
    collected_at: iso(-1, 3, 0),
  },
  {
    id: 'mock-festa-3',
    source: 'festa',
    source_event_id: 'kr-llm-fine-tune',
    source_url: 'https://festa.io/events/kr-llm-ft',
    title: '한국어 LLM 파인튜닝 핸즈온',
    description: 'LoRA, QLoRA 실습. GPU 자원 일부 제공.',
    start_at: iso(11, 13, 0),
    end_at: iso(11, 18, 0),
    timezone: 'Asia/Seoul',
    location_type: 'offline',
    location_name: '강남구 코엑스 컨퍼런스룸',
    city: '서울',
    country: 'KR',
    host_name: 'KR-LLM Society',
    price: '60,000원',
    categories: ['LLM', 'Workshop'],
    keywords_matched: ['LLM', 'Fine-tuning', 'LoRA'],
    thumbnail_url: null,
    is_ai_related: true,
    collected_at: iso(-1, 3, 0),
  },
];

export const MOCK_SOURCE_RUN_LOGS: SourceRunLog[] = [
  {
    id: 'run-1',
    source: 'festa',
    started_at: iso(-1, 3, 0),
    finished_at: iso(-1, 3, 1),
    status: 'success',
    events_collected: 32,
    events_new: 4,
    events_updated: 28,
    error_message: null,
    triggered_by: 'cron',
  },
  {
    id: 'run-2',
    source: 'eventus',
    started_at: iso(-1, 3, 0),
    finished_at: iso(-1, 3, 2),
    status: 'success',
    events_collected: 21,
    events_new: 2,
    events_updated: 19,
    error_message: null,
    triggered_by: 'cron',
  },
  {
    id: 'run-3',
    source: 'luma',
    started_at: iso(-1, 3, 0),
    finished_at: iso(-1, 3, 1),
    status: 'failed',
    events_collected: 0,
    events_new: 0,
    events_updated: 0,
    error_message: 'Timeout after 60s',
    triggered_by: 'cron',
  },
  {
    id: 'run-4',
    source: 'dev_event',
    started_at: iso(-1, 3, 0),
    finished_at: iso(-1, 3, 1),
    status: 'success',
    events_collected: 14,
    events_new: 1,
    events_updated: 13,
    error_message: null,
    triggered_by: 'cron',
  },
  {
    id: 'run-5',
    source: 'devpost',
    started_at: iso(-1, 3, 0),
    finished_at: iso(-1, 3, 1),
    status: 'partial',
    events_collected: 18,
    events_new: 3,
    events_updated: 15,
    error_message: 'RSS feed slow for 2 listings',
    triggered_by: 'cron',
  },
];

export const MOCK_SUBSCRIPTIONS: Subscription[] = [
  {
    id: 'sub-1',
    name: '내 RAG/Agent 구독',
    keywords: ['RAG', 'Agent', 'LangChain'],
    sources: null,
    location_types: ['offline', 'online'],
    cities: ['서울', '판교'],
    notify_on_new: true,
    notify_on_deadline: true,
    is_active: true,
    created_at: iso(-7, 9, 0),
  },
];

export const MOCK_BOOKMARKS: Bookmark[] = [
  {
    id: 'bm-1',
    event_id: 'mock-luma-1',
    event: MOCK_EVENTS[0],
    note: '꼭 참석',
    created_at: iso(-2, 14, 0),
  },
];
